config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
#get "/pages/*id" => 'pages#show', as: :page, format: false

 get 'calculator/clear' => 'calculator#clear'
  get 'calculator' => 'calculator#show'

  post 'calculator/:step' => 'calculator#create'
  get 'calculator/:step' => 'calculator#show'

get "/pages/*id" => 'pages#show', as: :page, format: false

root 'pages#show', id: 'index'


end

app/views/layouts/application.html.erb
<!doctype html>
<!--[if IE 9]>    <html class="ie9" lang="en"> <![endif]-->
<!--[if IE 10]>    <html class="ie10" lang="en"> <![endif]-->
<!--[if IE 11]>    <html class="ie11" lang="en"> <![endif]-->
<!--[if gt IE 11]><!--> <html class="gt-ie11" lang="en"> <!--<![endif]-->
    <head>
     <meta charset="utf-8">
       <!-- <% if content_for?(:title) %>
	        <%= yield(:title) %>
	        <% else %> -->
	        <title>DiamondPriceInfo.com - Max's Diamond Price Guide</title>
        <!-- <% end %> -->
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
         <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

           <%= stylesheet_link_tag    'prettyPhoto', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'responsive', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'style', media: 'all', 'data-turbolinks-track': 'reload' %>
 <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'html5', 'data-turbolinks-track': 'reload' %>
   <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
       
        <link rel="shortcut icon" href="favicon.ico">
        <!--[if lt IE 9]>
            <script src="js/html5.js"></script>
        <![endif]-->

   
    <%= csrf_meta_tags %>

  
   
  </head>

  <body>
   <!-- MAIN MENU -->
        <nav>
            <ul class="top-menu clearfix">
                <li class="logo"><%= image_tag 'logo4.jpg' %></li>
                <li class="menu-item"><a href="http://diamondpriceinfo.com">HOME</a></li>
                <li class="menu-item"> <%= link_to 'ABOUT', page_path('about_us') %> </li>
                <li class="menu-item"><%= link_to 'DIAMOND PRICES', calculator_path %> </li> 
                <li class="menu-item"><%= link_to 'LEARN ABOUT DIAMONDS', page_path('learn_about_diamonds') %> </li> 
                <li class="menu-item"><%= link_to 'BUYING GUIDE', page_path('guide_to_online_jewelry_retailers') %> </li>
                <li class="menu-item"><%= link_to 'CONTACT', page_path('contact_us') %> </li> 
                 <li class="resp-menu">
                    <select name="resp-menu" id="resp-menu" class="turnintodropdown">
                        <option value="/">Max's Diamond Price Guide</option>
                        <option value="pages/about_us">ABOUT</option>
                        <option value="calculator">Diamond Prices</option>
                        <option value="pages/learn_about_diamonds">Learn About Diamonds</option>
                        <option value="pages/guide_to_online_jewelry_retailers">Buying GUide</option>
                        
                        <option value="/pages/contact">CONTACT</option>
                    </select>
                </li> 
               
            </ul>
        </nav>
        <!-- MAIN MENU -->

 <!-- HEADER -->
        <div class="header-wrapper">
            <header id="top">
                <div class="clearfix">
                    <article>
                        <h1>MAX'S<span>DIAMOND PRICE GUIDE</span></h1>
                        <h3>FIND YOUR DIAMOND'S REALMARKET VALUE</h3>
                        <p><strong>We're Your Independent Source for Diamond Pricing.</strong></p>
                        
                    </article>
                    <figure>
                    <!-- google ad or CJ ad goes here -->
                         <a href="http://www.jdoqocy.com/click-7744481-11436191" target="_blank">
    <img src="http://www.ftjcfx.com/image-7744481-11436191" width="300" height="250" alt="" border="0"/></a>
                    
                    </figure>
                    <%= link_to 'Read Our Buying Guide', page_path('guide_to_online_jewelry_retailers'), class: "button blue" %> 
                </div>
            </header>
        </div>
        <!-- HEADER -->
    <%= yield %>


        <!-- CONTACTS -->
        <section id="contact" class="contacts clearfix">
            <h4>QUESTIONS ABOUT DIAMOND PRICING?  <span>SEND US A MESSAGE</span></h4>
            <form action="mailto:info@diamondpriceinfo.com" method="post" id="contactForm">
                <ul class="left">
                    <li><input type="text" class="input-field required" name="name" placeholder="Name" value="" /></li>
                    <li><input type="text" class="input-field required" name="subject" placeholder="Subject" value="" /></li>
                </ul>
                <ul class="right">
                    <li><textarea class="mailcontant" name="body" cols="5" rows="5" placeholder="Message"></textarea></li>
          <li><input type="text" class="input-field input-field-b required" name="question" placeholder="Security Question: 3+7 = " value="" /></li>
                </ul>
        <p><input type="submit" name="submit" value="Start Your Message" class="submit"/></p>
                <p id="success"><img id="loading" src="/assets/loading.gif" alt="Sending....." /></p>
            </form>
            <ul class="social-nav clearfix">
                <li><a href="https://www.facebook.com/diamondpriceguide/" class="fb">&nbsp;</a></li>
                <li><a href="https://twitter.com/maxspriceguides" class="tw">&nbsp;</a></li>
            </ul>
            <div class="contact">
                <p> Email:</p>
                <p class="contact-email">contact@diamondpriceinfo.com</p>
                             
            </div>
        </section>
        <!-- CONTACTS -->

        <!-- FOOTER -->
        <footer>
            <p><strong>DiamondPriceInfo.com</strong> &copy; Copyright 2017.</p>
            
        </footer>
  </body>
  <!-- jquery-->
  <script src="http://code.jquery.com/jquery-1.11.1.min.js"></script>
   <script src="http://code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
</html>

app/views/layouts/application_old.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= favicon_link_tag '/favicon.ico' %>
  <link rel="canonical" href="http://www.diamondpriceinfo.com/" />

  <%= stylesheet_link_tag "application", media: "all" %>
  <%= stylesheet_link_tag "learn_about_diamonds", media: "all" %>
  <%= javascript_include_tag "application" %>
  <title>
    <% if content_for?(:title) %>
      <%= yield(:title) %>
    <% end %>
  </title>
  <meta name="description" content="<%= yield(:description) %>" />
  <meta name="keywords" content="<%= yield(:keywords) %>" />
  <%= csrf_meta_tags %>
</head>

<body>

  <div id="wrapper">
    
    <div id="header">
      <%= render 'shared/logo_and_header'%>
      <%= render 'shared/menu'%>
    </div>
  
    <div id="contentBox">
      <div class="main-block">
        <div class="leftBottom">
          <div class="bottomSpaceAbout">
            <%= yield %>
          </div>
        </div>
      </div>

  <%= render 'shared/footer'%>
  <%= render 'shared/ga'%>

  </div>

</body>
</html>

app/views/layouts/calculator.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= favicon_link_tag '/favicon.ico' %>
  <link rel="canonical" href="http://www.diamondpriceinfo.com/" />

  <%= stylesheet_link_tag "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <title>
    <% if content_for?(:title) %>
      <%= yield(:title) %>
    <% end %>
  </title>
  <meta name="description" content="<%= yield(:description) %>" />
  <meta name="keywords" content="<%= yield(:keywords) %>" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= csrf_meta_tags %>
</head>

<body>

        <!-- MAIN MENU -->
        <nav>
            <ul class="top-menu clearfix">
                <li class="logo"><%= image_tag 'logo4.jpg' %></li>
               <li class="menu-item"><a href="http://diamondpriceinfo.com">HOME</a></li>
                <li class="menu-item"> <%= link_to 'ABOUT', page_path('about_us') %> </li>
                <li class="menu-item"><%= link_to 'DIAMOND PRICES', calculator_path %> </li> 
                <li class="menu-item"><%= link_to 'LEARN ABOUT DIAMONDS', page_path('learn_about_diamonds') %> </li> 
                <li class="menu-item"><%= link_to 'BUYING GUIDE', page_path('guide_to_online_jewelry_retailers') %> </li>
                <li class="menu-item"><%= link_to 'CONTACT', page_path('contact_us') %> </li> 
                <li class="resp-menu">
                    <select name="resp-menu" id="resp-menu" class="turnintodropdown">
                        <option value="/">Max's Diamond Price Guide</option>
                        <option value="pages/about_us">ABOUT</option>
                        <option value="calculator">Diamond Prices</option>
                        <option value="pages/learn_about_diamonds">Learn About Diamonds</option>
                        <option value="pages/guide_to_online_jewelry_retailers">Buying GUide</option>
                        
                        <option value="pages/contact">CONTACT</option>
                    </select>
                </li>
               
            </ul>
        </nav>
        <!-- MAIN MENU -->

        <!-- HEADER -->
        <div class="header-wrapper">
            <header id="top">
                <div class="clearfix">
                    <article>
                        <h1>MAX'S<span>DIAMOND PRICE GUIDE</span></h1>
                        <h3>FIND YOUR DIAMOND'S REALMARKET VALUE</h3>
                        <p><strong>We're Your Independent Source for Diamond Pricing.</strong></p>
                        
                    </article>
                    <figure>
                    <!-- google ad or CJ ad goes here -->
                         <a href="http://www.jdoqocy.com/click-7744481-11436191" target="_blank">
    <img src="http://www.ftjcfx.com/image-7744481-11436191" width="300" height="250" alt="" border="0"/></a>
                    
                    </figure>
                    <%= link_to 'Read Our Buying Guide', page_path('guide_to_online_jewelry_retailers'), class: "button blue" %>
                </div>
            </header>
        </div>
        <!-- HEADER -->

        <!-- TAGLINE -->
        <div class="tagline">
          <%= yield %>
</div>

            
             
            <div class="tagline">
            <h2><p style="font-size:14px;">"Before you buy or sell a diamond, you need to make sure the price is right. Our editors verify and update prices weekly to give you useful, relevant market pricing information. Whether you are preparing to buy a diamond for an engagement ring, need help to find out the value of a diamond in estate jewelry, want to know for how much you should insure your diamond, or want to value your investment diamond, you can easily check this pricing guide to get a RealMarket Value." -- MAX</p></h2>
            </div> 
        </div>

        <!-- AD SPACE-->

        <div class="tagline">
    <a href="http://www.jamesallen.com/engagement-rings/settings-with-sidestones/?a_aid=4f11db8dbdbdf&amp;a_bid=cdc9c915" target="_new">
    <img src="http://www.jamesallen.com/b/engagement-rings/sidestones/diamond-with-side-stones-728x90.jpg" alt="Rings With Side Stones" title="Rings With Side Stones" border="0"></a>
    <img style="border:0" src="http://affiliates.jamesallen.com/scripts/imp.php?a_aid=4f11db8dbdbdf&amp;a_bid=cdc9c915" width="1" height="1" alt="">
 </div>
        <!-- TAGLINE -->

        <!-- FEATURES -->
        <section id="feature" class="features">
            <h4>LEARN ABOUT DIAMONDS - <span> The more you know, the better deal you can get!</span></h4>
            <ul class="clearfix">
                <li>
                    <%= link_to image_tag('diamond_color1.gif'), page_path('archive/color_grade') %> 
                    <h6>Color</h6>
                    <p>Color in diamonds most often appears as a pale yellow or slightly brown hue. The yellow color is due to the presence of trace amounts of nitrogen in the diamond.</p>
                    <p>Read More</a></p>
                </li>
                <li>
                <%= link_to image_tag('diamond_cut1.gif'), page_path('archive/cut_grade') %> 
                    <h6>Cut</h6>
                    <p>A diamond can be of the best Clarity and Color grades, but if its Cut Grade is poor, the diamond will not be the beautiful gem you will want to buy.</p>
                     <p>Read More</a></p>
                </li>
                <li><%= link_to image_tag('diamond_clarity1.gif'), page_path('archive/clarity_grade') %> 
                    <h6>Clarity</h6>
                    <p>Gem-quality diamonds are evaluated and graded by their clarity, the absence of naturally occurring internal flaws, called Inclusions, and external flaws, called Blemishes.</p>
                     <p>Read More</a></p>
                </li>
                <li><%= link_to image_tag('diamond_carat_weight1.gif'), page_path('archive/what_is_a_carat') %>
                    <h6>Carat Weight</h6>
                    <p>The carat of a diamond refers to the weight of the stone. A carat is equal to about .2 grams, which can be compared to the weight of a standard size paper clip. </p>
                     <p>Read More</a></p>
                </li>
            </ul>
        </section>
        <!-- FEATURES -->

                

       <!-- CONTACTS -->
        <section id="contact" class="contacts clearfix">
            <h4>QUESTIONS ABOUT DIAMOND PRICING?  <span>SEND US A MESSAGE</span></h4>
            <form action="mailto:info@diamondpriceinfo.com" method="post" id="contactForm">
                <ul class="left">
                    <li><input type="text" class="input-field required" name="name" placeholder="Name" value="" /></li>
                    <li><input type="text" class="input-field required" name="subject" placeholder="Subject" value="" /></li>
                </ul>
                <ul class="right">
                    <li><textarea class="mailcontant" name="body" cols="5" rows="5" placeholder="Message"></textarea></li>
          <li><input type="text" class="input-field input-field-b required" name="question" placeholder="Security Question: 3+7 = " value="" /></li>
                </ul>
        <p><input type="submit" name="submit" value="Start Your Message" class="submit"/></p>
                <p id="success"><img id="loading" src="/assets/loading.gif" alt="Sending....." /></p>
            </form>
            <ul class="social-nav clearfix">
                <li><a href="https://www.facebook.com/diamondpriceguide/" class="fb">&nbsp;</a></li>
                <li><a href="https://twitter.com/maxspriceguides" class="tw">&nbsp;</a></li>
            </ul>
            <div class="contact">
                <p> Email:</p>
                <p class="contact-email">contact@diamondpriceinfo.com</p>
                             
            </div>
        </section>

        <!-- FOOTER -->
        <footer>
            <p><strong>DiamondPriceInfo.com</strong> &copy; Copyright 2017.</p>
            
        </footer>
        <!-- FOOTER -->

        <!-- jQuery -->
        <script src="http://code.jquery.com/jquery-1.11.1.min.js"></script>
        <script src="http://code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
        <!--
        <script src="js/jquery.jcarousel.min.js"></script>
        <script src="js/jquery.prettyPhoto.js"></script>
        <script src='js/jquery.scrollTo-min.js'></script>
        <script src='js/jquery.validate.min.js'></script>
        <script src='js/jquery.form.js'></script>
        <script src="js/selectbox.js"></script>
        <script src="js/custom.js"></script>
        -->
    </body>
</html>
           
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= favicon_link_tag '/favicon.ico' %>
  <link rel="canonical" href="http://www.diamondpriceinfo.com/" />

  <%= stylesheet_link_tag "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <title>
    <% if content_for?(:title) %>
      <%= yield(:title) %>
    <% end %>
  </title>
  <meta name="description" content="<%= yield(:description) %>" />
  <meta name="keywords" content="<%= yield(:keywords) %>" />
  <%= csrf_meta_tags %>
</head>

<body>
 
<div id="wrapper">
  <div id="header">
    <%= render 'shared/logo_and_header'%>
    <%= render 'shared/menu'%>
  </div>

  <%= yield %>

  <%= render 'shared/footer'%>
  <%= render 'shared/ga'%>
</div>



</body>
</html>

app/views/layouts/linking.html.erb
<div class="about-Us">
  <h2>Linking Policy</h2><br><br>
  <p>diamondpriceinfo.com
    <br><br>
    Last Updated: 01/17/11 
    <br><br>

    We encourage you to link to our website, Max's Diamond Price Guide found here at: <a href="http://www.diamondpriceinfo.com" target="_blank">http://www.diamondpriceinfo.com</a>, and the various section entrance pages and specific articles within.    
    <br><br>
    OTHER IMPORTANT DIAMONDPRICEINFO.COM POLICIES:
    <br>
    •<a href="/pages/privacy">Privacy Policy</a>
    <br>
    •<a href="/pages/copyright">Trademark Use Policy</a>
    <br>
    •<a href="/pages/terms_of_use">Terms of Service</a></p>


</div>
<div class="about-right">
  <%= image_tag "rings.jpg" %>
</div>

